app/routes.py
from flask import Blueprint, render_template, make_response, flash, redirect, url_for, request, Response
from flask_login import login_required, LoginManager, current_user
import random
from typing import cast
from . import db
from datetime import datetime, timedelta
from .database import *
from sqlalchemy import desc, and_



routes = Blueprint('routes', __name__)

def get_random_card(probability=None):
    from .database import Card
    rarity = ['common', 'rare', 'epic', 'legendary']
    if probability is None:
        probability = [0.60, 0.25, 0.14, 0.01]
    chosen_rarity = random.choices(rarity, weights=probability)[0]
    rarity_list = Card.query.filter_by(rarity = chosen_rarity).all()
    if not rarity_list:
        return None
    return random.choice(rarity_list)
  

@routes.route('/')
@routes.route('/index')
def index():
    posts = Post.query.all()
    return render_template('index.html', title='Home', posts=posts)

@routes.route('/delete-post', methods=['POST'])
def delete():
    post_id = request.form.get('post_id')   # Post being completed
    u = current_user                        # User completing

    post = db.session.get(Post, post_id)

    # Confirm the both users have the required cards
    if not post:
        return Response(" Delete failed: post does not exist!", status = 400)
    
    # Mark trade as completed
    post.completed = True
    new_action = UserAction(action_type = 'DELETE_'+str(post.post_id), user_id = u.user_id)
    db.session.add(new_action) 
    db.session.commit()
    
    return "Post deleted!"


@routes.route('/update-post', methods=['POST'])
def trade():
    post_id = request.form.get('post_id')   # Post being completed
    u = current_user                        # User completing

    post = db.session.get(Post, post_id)
    trade_uid = post.owner_id
    trade_user = db.session.get(User, trade_uid)

    # Confirm the both users have the required cards
    for card in post.cards_traded:
        if card not in trade_user.cards:
            return Response(trade_user.username + " does not have the required card/s to complete this trade!", status = 400)
    
    for card in post.cards_wanted:
        if card not in u.cards:
            return Response("You don't have the required card/s to complete this trade!", status = 400)
    
    # Complete the trade
    for card in post.cards_traded:

        trade_user.remove_card(card)
        u.add_card(card)

    for card in post.cards_wanted:
        trade_user.add_card(card)
        u.remove_card(card)
    
    # Mark trade as completed
    post.completed = True
    new_action = UserAction(action_type = 'TRADE_'+str(post.post_id), user_id = u.user_id)
    db.session.add(new_action) 
    db.session.commit()
    
    return "Congratulations! You've completed the trade!"

@routes.route('/post', methods=['GET','POST'])
def post():
    cards = Card.query.all()
    if request.method == 'POST':
        message = request.form.get('message')
        cards_traded = request.form.getlist('cards_traded')
        cards_wanted = request.form.getlist('cards_wanted')

        u = current_user
        new_post = Post(owner_id=u.user_id, message=message, completed=False)

        if len(cards_traded) == 0:
            flash('Select at least one card to trade', 'error')
            return redirect('/post')
        if len(cards_wanted) == 0:
            flash('Select at least one card you want in return', 'error')
            return redirect('/post')
        db.session.add(new_post)

        # Add traded cards to the post
        for card_id in cards_traded:
            card = db.session.get(Card, card_id)
            if card:
                new_post.cards_traded.append(card)
        
        # Add wanted cards to the post
        for card_id in cards_wanted:
            card = db.session.get(Card, card_id)
            if card:
                new_post.cards_wanted.append(card)

        db.session.flush()        
        new_action = UserAction(action_type = 'POST_'+str(new_post.post_id), user_id = u.user_id)
        db.session.add(new_action)
        db.session.commit()
        flash('Post Created!', 'success')
    return render_template('post.html', title='Make a post', cards=cards)

@routes.route('/user/<username>')
def user(username):
    user = User.query.filter_by(username=username).first()
    cards = Card.query.all()
    n_posts = len(user.posts)
    n_cards = len(cards)
    n_owned = len(user.cards)
    return render_template('user.html', user=user, cards=cards, n_posts=n_posts, n_cards=n_cards, n_owned=n_owned)

@routes.route('/discard-card', methods=['POST'])
def discard():
    card_id = request.form.get('card_id')   # card being discarded
    u = current_user                        # User completing
    card = Card.query.get(card_id)

    if card.rarity == 'legendary':
        u.money += 500
    elif card.rarity == 'epic':
        u.money += 250
    elif card.rarity == 'rare':
        u.money += 100
    elif card.rarity == 'common':
        u.money += 50
    
    u.remove_card(card)
    
    # Log user action
    new_action = UserAction(action_type = 'DISCARD_'+str(card_id), user_id = u.user_id)
    db.session.add(new_action) 
    db.session.commit()
    
    return "Card discarded succesfully!"


@routes.route('/how_it_works')
def rules():
    return render_template('rules.html', title='How it works')

@login_required
@routes.route('/934910939049', methods=['GET','POST'])
def new_card():
    if current_user.user_id != 1:
        return render_template('rules.html', title='How it works')
    if request.method == 'POST':
        name = request.form.get('name')
        rarity = request.form.get('rarity')
        url = "/static/img/cards/" + request.form.get('url') + ".png"

        new_card = Card(rarity=rarity, name=name, url=url)

        db.session.add(new_card)
        db.session.commit()
    return render_template('new_card.html', title='Mint a new card')


@routes.route('/packs')
@login_required
def packs():
    user = cast(User, current_user)
    # Get the time of the last free pack action
    last_free_pack_action = UserAction.query.filter_by(user_id=user.user_id, action_type='PACK_FREE').order_by(UserAction.date.desc()).first()
    if last_free_pack_action:
        time_since_last_pack = datetime.now() - last_free_pack_action.date
        if time_since_last_pack < timedelta(hours=24):
            #Calculate the remaining time
            remaining_time = timedelta(hours=24) - time_since_last_pack
        else:
            remaining_time = timedelta(seconds=0)
    else:
        remaining_time = timedelta(seconds=0)
    return render_template('packs.html', title='Packs', remaining_time=remaining_time.total_seconds())


@routes.route('/open_pack', methods=['POST'])
@login_required
def open_pack():
    user = cast(User, current_user)
    # Get the time of the last free pack action
    last_free_pack_action = UserAction.query.filter_by(user_id=user.user_id, action_type='PACK_FREE').order_by(UserAction.date.desc()).first()
    if last_free_pack_action:
        time_since_last_pack = datetime.now() - last_free_pack_action.date
        if time_since_last_pack < timedelta(hours=24):
            return Response("Free pack not ready yet!", status = 400)

    items = [get_random_card(probability=[0.60, 0.25, 0.14, 0.01]) for _ in range(5)]
    #Removes repeating cards
    unique_items = set(items)

    #Check for cards in database
    if None in unique_items:
        flash("An error occurred while opening the pack. Please contact administrators.", "error")
        return "None"
    
    for card in unique_items:
        user.add_card(card)
    user.money += 1000
    new_action = UserAction(action_type = 'PACK_FREE', user_id = current_user.user_id)
    db.session.add(new_action)
    db.session.commit()
    print("ACTION ADDED")
    return render_template('open_pack.html', items=unique_items)

@routes.route('/open_pack_paid', methods=['POST'])
@login_required
def open_pack_paid():
    user = cast(User, current_user)
    if user.money < 1000:
        flash("Not enough money!")
        return "None"
    
    items = [get_random_card(probability=[0.40, 0.30, 0.20, 0.10]) for _ in range(5)]
    unique_items = set(items)

    user.money -= 1000

    if None in unique_items:
        flash("An error occurred while opening the pack. Please contact administrators.", "error")
        return "None"
    
    for card in unique_items:
        user.add_card(card)

    new_action = UserAction(action_type = 'PACK_PAID', user_id = current_user.user_id)
    db.session.add(new_action)
    db.session.commit()
    print("ACTION ADDED")

    return render_template('open_pack.html', items=unique_items)
    
    
@routes.route('/inbox')
@login_required
def inbox():
    return render_template('inbox.html', title='Inbox')

app/templates/_post.html
<!-- jinja sub-template for posts -->

<!doctype html>
<html lang="en">
<div class="block {% if post.completed == True %}completed{% endif %}">
    <div id="post-details">
       <img src="{{ post.author.avatar(128) }}" alt="Author's avatar">
       <div id="details-text">
         <a style="color:#212529" href="/user/{{ post.author.username }}"><span id="author-name">{{ post.author.username }} {% if current_user.user_id == post.owner_id%} (You){% endif %}</span></a>
       <span id="date">{{ post.date.strftime("%A, %d %B %Y %I:%M:%S %p") }}</span>
       </div>
    </div>
    <p id="post-message">{{ post.message }}</p>

    <h4> Cards gave up </h4>
    <div class="cards-container">
    {% for card in post.cards_traded %}
    <custom-card name="{{ card.name }}" year="{{ card.year }}" artist="{{ card.artist }}" rarity="{{ card.rarity }}" img="{{ card.url }}"></custom-card>
    {% endfor %}
    </div>

    <h4> Cards received </h4>
    <div class="cards-container">
    {% for card in post.cards_wanted %}
    <custom-card name="{{ card.name }}" year="{{ card.year }}" artist="{{ card.artist }}" rarity="{{ card.rarity }}" img="{{ card.url }}"></custom-card>
    {% endfor %}
    </div>

    {% if current_user.is_authenticated and post.completed != True and current_user.user_id != post.owner_id %}
    <form class="trade-form">
       <input type="hidden" name="post_id" value="{{ post.post_id }}">
       <input type="hidden" name="trade_user" value="{{ current_user }}">
       <button type="button" class="btn btn-primary trade-btn">Trade</button>
    </form>
    {% elif current_user.is_authenticated and post.completed != True and current_user.user_id == post.owner_id %}
    <form class="delete-form">
       <input type="hidden" name="post_id" value="{{ post.post_id }}">
       <button type="button" class="btn btn-primary delete-btn">Delete</button>
    </form>
    {% endif %}

    {% if post.completed == True %}
    <h4 style="color:grey; font-size: 20px;">Trade Ended!</h4>
    {% endif %}

   <div id="confirmModal" class="modal fade" tabindex="-1" role="dialog">
      <div class="modal-dialog">
         <div class="modal-content">
            <div class="modal-header">
               <h4 id="confirmModalTitle" class="modal-title">Contents:</h4>               
               <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
               <div id="confirmModalContents"></div>
            </div>
            <div class="modal-footer">
               <button type="button" class="btn btn-primary" data-dismiss="modal" id="confirmButton">Confirm</button>
               <button type="button" class="btn btn-secondary" data-dismiss="modal" id="cancelButton">Cancel</button>
            </div>
         </div>
      </div>
   </div>

   <div id="dialogModal" class="modal fade" tabindex="-1" role="dialog">
      <div class="modal-dialog">
         <div class="modal-content">
            <div class="modal-header">
               <h4 id="modalTitle" class="modal-title">Contents:</h4>               
               <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
               <div id="modalContents"></div>
            </div>
            <div class="modal-footer">
               <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
         </div>
      </div>
   </div>

 </div>

app/templates/base.html
<!doctype html>
<html lang="en">
    <head>
      <title>
      {% if title %}
      {{ title }}
      {% else %}
      Card Trading
      {% endif %}
      </title>

      <!-- Include Boostrap CSS -->
      <link
        rel="stylesheet"
        href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
        crossorigin="anonymous"
      >

      <!-- Custom CSS Stylesheets -->

      <link rel="stylesheet" href="../static/css/style.css">
      <link rel="stylesheet" href="../static/css/marketplace.css">
      <link rel="stylesheet" href="../static/css/card.css">

      <!-- Google Fonts -->
      <link rel="preconnect" href="https://fonts.googleapis.com">
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
      <link href="https://fonts.googleapis.com/css2?family=Urbanist:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
      <link href="https://fonts.googleapis.com/css2?family=Taviraj:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Urbanist:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
      <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap" rel="stylesheet">

      <!-- Include font awesome CSS -->
      <link
        rel="stylesheet"
        href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
        crossorigin="anonymous"
      >

      <!-- Include JQuery -->
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
      
      <!-- Popper JS -->
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>

      <!-- Latest compiled JavaScript -->
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
      
      <!-- JavaScript -->
      <script src="../static/js/script.js"></script>
      <script src="../static/js/trade.js"></script>
      <script src="../static/js/discard.js"></script>
      
    </head>
    <body>
  
        <div id="header">
          <a id="logo" href="/index"><img src="../static/img/logo.svg" alt="Website Logo"></a>
            <div class="navbar navbar-expand-lg navbar-light bg-light">
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                  <li class="nav-item">
                    <a class="nav-link" href="/index">Marketplace</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="/how_it_works">How it Works</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="/packs">Packs</a>
                  </li>
                </ul>
              </div>
            </div>

            <div id="auth">
              {% if current_user.is_authenticated %}

              <div id="header-profile">
                <a href="{{ url_for('routes.user', username=current_user.username) }}" class="nav-btn profile-btn">
                  <img src="{{ current_user.avatar(32) }}" id="header-pfp" alt="User Avatar" >
                  <span>Balance: ${{ current_user.money }}</span>
                </a>
              </div>
              <div class="dropdown">
                <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Welcome, {{ current_user.username }}!
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                  <a class="dropdown-item" href="/logout">Logout</a>
                </div>
              </div>
              {% else %}
                <a href="/login" class="btn primary-btn">Log in</a>
                <a href="/signup" class="btn secondary-btn">Sign up</a>
              {% endif %}
            </div>
            
        </div>
      
        <div id="container">
        {% block content %}{% endblock %}
        </div>

    </body>
</html>

app/templates/index.html
{% extends "base.html" %}

{% block content %}

   <div class="page-title">
   <h1>Marketplace Feed</h1>
   <p> View community trade posts or make a post of your own!</p>

   {% if current_user.is_authenticated %}
      <a href="/post" class="btn btn-primary">Make a post!</a>
   {% endif %}
   </div>  

   <h2> Community posts</h2>
   <div id="posts">
   {% for post in posts|reverse %}
      {%include '_post.html' %}
   {% endfor %}
   </div>
   
{% endblock %}

app/templates/login.html
{% extends "base.html" %}

{% block content %}
<form method="POST" class="center-form">
   <h3>Login</h3>
   <div class="form-group">
     <label for="email">Email</label>

     <input
       type="email"
       class="form-control"
       id="email"
       name="email"
       placeholder="Email"
     >
   </div>
   <div class="form-group">
     <label for="password">Password</label>

     <input
       type="password"
       class="form-control"
       id="password"
       name="password"
       placeholder="Password"
     >
   </div>

   {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                <div class="alert alert-{{ category }}" role="alert">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}

   <button type="submit" class="btn btn-primary">Submit</button>
 </form>
{% endblock %}

app/templates/open_pack.html
{% block content %}
    {% for card in items %}
        <custom-card 
        name="{{ card.name }}" 
        year="{{ card.year }}" 
        artist="{{ card.artist }}" 
        rarity="{{ card.rarity }}" 
        img="{{ card.url }}" 
        style="margin:auto">
        </custom-card>
    {% endfor %}
{% endblock %}

app/templates/packs.html
{% extends "base.html" %}

{% block content %}
   <!-- Write all HTML code here -->

   <h1>This is where you purchase packs!</h1>
   <p> Choose one of our packs:</p>

   <button id="free_pack_button" class="btn btn-info btn-lg">Loading...</button>

   <button id="paid_pack_button" class="btn btn-info btn-lg">Paid Pack</button>

   <div id="packItemsContainer"></div>
   {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
         {% for category, message in messages %}
               <div class="alert alert-{{ category }}" role="alert">
                  {{ message }}
               </div>
         {% endfor %}
      {% endif %}
   {% endwith %}
   
   {% block scripts %}
      <script>
         var remaining_time = {{ remaining_time }};
         console.log(remaining_time);
         startCountdownTimer(remaining_time);

         function startCountdownTimer(duration) {
            var timer = duration, hours, minutes, seconds;
            //Coutdown for daily pack
            var countdown = setInterval(function () {
               hours = parseInt(timer / 3600, 10);
               minutes = parseInt((timer % 3600) / 60, 10);
               seconds = parseInt(timer % 60, 10);

               hours = hours < 10 ? "0" + hours : hours;
               minutes = minutes < 10 ? "0" + minutes : minutes;
               seconds = seconds < 10 ? "0" + seconds : seconds;

               document.getElementById("free_pack_button").textContent = "Next free pack in: " + hours + ":" + minutes + ":" + seconds;

               if (--timer < 0) {
                     timer = duration;
                     clearInterval(countdown);
                     document.getElementById("free_pack_button").textContent = "Daily Free Pack!";
                     document.getElementById("free_pack_button").addEventListener('click', function () {
                        fetch('/open_pack',{method: "POST"})
                           .then(response => {
                              if (!response.ok) {
                                 document.getElementById('modalPackContents').innerHTML = response.text;
                              }
                              return response.text()})
                           .then(html => {
                              if (html == "None") {
                                 location.reload();
                              }
                              else{
                                 //To store fetched html, to display after page refresh for countdown update
                                 localStorage.setItem('fetchedHTML', html);
                                 location.reload();
                              }
                           })
                     });      

               }
            }, 1000);
         }     
         document.getElementById('paid_pack_button').addEventListener('click', function () {
            fetch('open_pack_paid', {method: "POST"})
            .then(response => response.text())
            .then(html => {
               if (html == "None") {
                  alert('Purchase failed.');
               }
               else {
                  localStorage.setItem('fetchedHTML', html);
                  location.reload();
               }
            })
         });
         // After the page is reloaded, check if there is any saved HTML in localStorage
         window.onload = function() {
            var fetchedHTML = localStorage.getItem('fetchedHTML');
            if (fetchedHTML) {
               // Append the fetched HTML
               document.getElementById('modalPackContents').innerHTML = fetchedHTML;
               // Clear the saved HTML from localStorage
               localStorage.removeItem('fetchedHTML');
               $('#packModal').modal('show');
            }
         }               
      </script>
   {% endblock %}

   <div id="packModal" class="modal fade" tabindex="-1" role="dialog">
      <div class="modal-dialog">
         <div class="modal-content">
            <div class="modal-header">
               <h4 class="modal-title">Contents:</h4>               
               <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
               <div id="modalPackContents"></div>
            </div>
            <div class="modal-footer">
               <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
         </div>
      </div>
   </div>
{% endblock %}

app/templates/post.html
{% extends "base.html" %}

{% block content %}
{% if current_user.cards|length == 0 %}
    <p> You don't have any cards! </p>

{% else %}
<div class="block">
    <form method="POST" class="center-form">
    <h3>Write a new post!</h3>
    <div class="form-group">
        <label for="message">Post message:</label>
        <input
        type="text"
        class="form-control block-input-field"
        id="message"
        name="message"
        placeholder="Write your message here..."
        >
    </div>
    <div class="form-group">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="alert alert-{{ category }}" role="alert">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}
        <h4><label for="cards_traded">Cards to give up:</label></h4><br>
        <div class="cards-container">
        {% for card in current_user.cards %}
        <div class="card-choice">
        <label for="{{'traded_' ~ card.card_id }}">
            <custom-card name="{{ card.name }}" year="{{ card.year }}" artist="{{ card.artist }}" rarity="{{ card.rarity }}" img="{{ card.url }}" style="margin:auto" quantity="{{ current_user.cards.get(card) }}"></custom-card>
        </label>
        <input type="checkbox" id="{{'traded_' ~ card.card_id }}" name="cards_traded" value="{{ card.card_id }}">
        </div>
        {% endfor %}
        </div>
            
        
        <h4><label for="cards_wanted">Cards wanted:</label></h4><br>
        <div class="cards-container">
        {% for card in cards %}
        <div class="card-choice">
        <label for="{{'wanted_' ~ card.card_id }}">
            <custom-card name="{{ card.name }}" year="{{ card.year }}" artist="{{ card.artist }}" rarity="{{ card.rarity }}" img="{{ card.url }}" style="margin:auto"></custom-card>
        </label>
        <input type="checkbox" id="{{'wanted_' ~ card.card_id }}" name="cards_wanted" value="{{ card.card_id }}">
        </div>
        {% endfor %}
        </div> 
    
    </div>
    <button type="submit" class="btn btn-primary">Post</button>
    </form>
</div>
{% endif %}
{% endblock %}

app/templates/rules.html
{% extends "base.html" %}

{% block content %}
   <h1>How it works!</h1>
   <h6>SoundSwap is a trading card game for music lovers! Collect your favourite albums and trade them with friends!</h6>
   </br>
   <p>
      To get your first cards, open your Daily Pack! Daily Packs can be opened once every 24 hours, and contain a small selection of
      cards and some free money. Money can be used to purchase gold packs, which contain cards of higher rarity! To check out your collection, 
      click on your profile picture/balance.
      Once you have some cards, you can trade them with other users on the marketplace! Open the marketplace tab and click 'Make a post'. Then,
      select which cards you want to offer and receive!
   </p>
   
{% endblock %}

app/templates/signup.html
{% extends "base.html" %}

{% block content %}
<script>
   //Check for validity of user entered information
   //Future sanitisation checks should also be implemented here
   function validateForm() {
      var password1 = document.getElementById('password1').value;
      var password2 = document.getElementById('password2').value;
      var username = document.getElementById('username').value
      var email = document.getElementById('email').value

      plength = password1.length;
      ulength = username.length;
      elength = email.length;

      //Check for length of password
      if (plength > 20 || plength == 0){
         alert('Password length must range from 1-20 letters.');
         return false;
      }
      //Check for password and confirmed password
      if (password1 != password2) {
         alert('Passwords do not match.');
         return false;
      }

      //Check for simple eamil validation including '@' is done by bootstrap type: 'email'
      if (elength < 3){
         alert('Please enter a valid email.');
      }

      //Checks for username length
      if (ulength > 10 || ulength == 0){
         alert('Username length must range from 1-10 letters.');
         return false;
      }

      return true;
   }
</script>
<form method="POST" onsubmit="return validateForm()" class="center-form">
   <h3>Sign Up</h3>
   <div class="form-group">
     <label for="email">Email Address</label>
     <input
       type="email"
       class="form-control"
       id="email"
       name="email"
       placeholder="Enter Email"
     >
   </div>
   <div class="form-group">
     <label for="username">Username</label>
     <input
       type="text"
       class="form-control"
       id="username"
       name="username"
       placeholder="Enter Username (Maximum 10 Letters)"
     >
   </div>
   <div class="form-group">
     <label for="password1">Password</label>
     <input
       type="password"
       class="form-control"
       id="password1"
       name="password1"
       placeholder="Enter Password (Maximum 20 Letters)"
     >
   </div>
   <div class="form-group">
     <label for="password2">Password (Confirm)</label>
     <input
       type="password"
       class="form-control"
       id="password2"
       name="password2"
       placeholder="Confirm Password"
     >
   </div>
   {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
          {% for category, message in messages %}
            {% if category == 'error' %}
                <div class="alert alert-{{ category }}" role="alert">
                    {{ message }}
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            {% endif %}
            {% if category == 'success' %}
                <div class="alert alert-{{ category }}" role="alert">
                  {{ message }}
                </div>
                <a href="{{ url_for('auth.login') }}" class="btn btn-primary">Login Now</a>
            {% endif %}
          {% endfor %}
        {% else %}
            <button type="submit" class="btn btn-primary">Submit</button>
        {% endif %}
    {% endwith %}
 </form>
{% endblock %}

app/templates/user.html
{% extends "base.html" %}

{% block content %}
<div class="block account">
<img src="{{ user.avatar(128) }}" alt="User's avatar">
<h1>{{ user.username }}</h1>
{% if user.about %}<p>{{ user.about }}</p>{% endif %}

<h3>{{ user.username }}'s Collection: {{ n_owned }}/{{ n_cards }}</h3>
<div class="cards-container">
{% for card in cards %}
    <div class="account_card">
        <custom-card {% if card not in user.cards%} class="not_owned" {% endif %} name="{{ card.name }}" year="{{ card.year }}" artist="{{ card.artist }}" rarity="{{ card.rarity }}" img="{{ card.url }}" quantity="{{ current_user.cards.get(card) }}"></custom-card>

        {% if current_user == user and card in user.cards%}
        <form class="discard-form">
            <input type="hidden" name="card_id" value="{{ card.card_id }}">
            <input type="hidden" name="rarity" value="{{ card.rarity }}">
            <button type="button" class="btn btn-primary discard-btn">Discard</button>
         </form>
        {% endif %}
    </div>
{% endfor %}
</div>

<h3>{{ user.username }}'s posts:</h3>
{% for post in user.posts %}
    {% include '_post.html' %}
{% endfor %}
{% if n_posts == 0 %}
    <h4>No posts yet! </h4>
{% endif %}
</div>
{% endblock %}